version: '3'
services:
  api:
    depends_on:
      - db
      - cache
    image: engincan/kap-disclosures:latest
    ports:
      - 3002:3002
    environment:
      - DATABASE_HOSTNAME=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - KAP_MEMBERS_APP_URL=http://members-api:3001
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=
      - AWS_SES_SENDER=
      - AWS_SES_RECEIVER=
      - AWS_SES_REGION=
      - CELERY_BROKER=redis://cache:6379/0
      - CELERY_BACKEND=redis://cache:6379/1
    volumes:
      - kap-disclosures-logs:/app/kap-disclosures/logs
  celery:
    depends_on:
      - db
      - cache
    image: engincan/kap-disclosures:latest
    volumes:
      - kap-disclosures-logs:/app/kap-disclosures/logs
    environment:
      - DATABASE_HOSTNAME=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - KAP_MEMBERS_APP_URL=http://members-api:3001
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=
      - AWS_SES_SENDER=
      - AWS_SES_RECEIVER=
      - AWS_SES_REGION=
      - CELERY_BROKER=redis://cache:6379/0
      - CELERY_BACKEND=redis://cache:6379/1
    command: celery -A app.tasks worker --loglevel=INFO -B -n kap-disclosure-worker@%n -Q kap-disclosure-queue
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - members-db:/var/lib/postgresql/data
  members-api:
    depends_on:
      - db
    image: engincan/kap-members-db
    ports:
      - 3001:3001
    environment:
      - DATABASE_HOSTNAME=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
  cache:
    image: redis
    ports:
      - 6379:6379
    environment: []
volumes:
  kap-disclosures-logs:
  members-db:
