name: build code and test

on:
  push:
    branches:
      - dev
    paths:
      - 'app/**'
      - '**/requirements.txt'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        id: python-setup
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Create log directory
        run:
          mkdir logs
          
      - name: Install dependencies
        id: install-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test with pytest
        id: test
    
        run: |
          pytest -v

      - name: Check on failures
        if: steps.test.outcome != 'success'
        run: exit 1

      - name: Create a pull request to master
        run: gh pr create -B master -H dev --title 'Merge dev into master' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_ACCESS_TOKEN }}